# UAT release workflow
#
# workflow will be triggered on pushing commits or pull request to master (main trunk),
# jobs include:
# - junit test
# - build and sign APK, upload APK to GitHub artifacts, deploy to Firebase App Distribution.
#
name: UAT Release CI

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  unitTest:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Unit tests
        run: ./gradlew test --stacktrace

  apk:
    name: Generate APK
    needs: unitTest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build APK
        run: ./gradlew assembleUatRelease --stacktrace

      - name: Sign APK
        # https://github.com/marketplace/actions/sign-android-release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/uat/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-uat-release
          path: ${{ env.SIGNED_RELEASE_FILE }}

  uatRelease:
    name: Deploy apk to testers
    needs: apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: app-uat-release

      - name: Deploy to Firebase App Distribution
        # https://github.com/marketplace/actions/firebase-app-distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          # $firebase login:ci to get token
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: i21-testers
          file: app-uat-release/app-uat-release-unsigned-signed.apk
          releaseNotesFile: releaseNotes.txt